/*
{
   "type":"FeatureCollection",
   "features":[
      {
         "type":"Feature",
         "properties":{
           "name": "BREDVIKEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               23.611507415771484,
               65.81084897946091
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "BODÖN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               23.48851203918457,
               65.81339861666154
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "STORSAND"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               22.023038864135742,
               65.62249644678872
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "LULVIKSBADET"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               22.15444564819336,
               65.54606255137291
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "LULHÄLLAN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               22.15240716934204,
               65.5192498070519
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "KLUBBVIKEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               22.36687660217285,
               65.49920890840932
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "STORSNÄCK"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               21.184558868408203,
               64.7744911104303
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SILLSKATAN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               21.217260360717773,
               64.74261155467666
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "VÅNÖREN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               21.54569149017334,
               64.51869417635449
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "BJURÖKLUBB SE"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               21.611223220825195,
               64.43492908208786
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "BJURÖKLUBB SW"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               21.58041000366211,
               64.43429941147684
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "LILLIS"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               20.02532958984375,
               63.66987214843851
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "LÄNKEBO"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               19.99958038330078,
               63.65235474197827
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "STORÄNGET"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               19.47747230529785,
               63.49141413873825
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SALUSAND"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               19.264183044433594,
               63.45756728705775
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "STUBBSAND"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.959655761718746,
               63.220636696106915
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "GULLVIK"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.82786273956299,
               63.214932082292805
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "VANNVIKEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.815631866455078,
               63.20794965080512
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "NYÄNGET"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.685641288757324,
               63.25064955421237
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "STORSANDEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.528785705566406,
               62.99013053076868
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SÄLSTEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.97191619873047,
               62.64485420666252
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SMITINGE"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.032941818237305,
               62.59942445768768
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SVARTVIK"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.91222095489502,
               62.57594228749241
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "YTTERFÄLLE"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.925631999969482,
               62.585744422903055
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "MYCKELÄNG"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.534780502319336,
               62.44946068012924
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "GULLFIBER"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.483882904052734,
               62.51049555437819
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SMACKEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.474527359008786,
               62.50966355942328
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "STORNÄSET"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.50019073486328,
               62.44942098076193
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "DYRÅSAND"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.458176612854004,
               62.07770856213146
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SÖRFJÄRDEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.422943115234375,
               62.026561098560606
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "VARPSAND"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.415218353271484,
               62.01806506729427
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "HÅRTE"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.39762306213379,
               61.99579703742656
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "HALLSBO"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               16.875600814819336,
               61.81523144939095
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "FÖNEBO"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               16.71396017074585,
               61.921139510833584
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "MALNBADEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.176995277404785,
               61.716725596166306
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "HÖLICK V"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.432942390441895,
               61.629652028202926
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "HÖLICK S"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.44530200958252,
               61.62251399199984
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "TÅNGVIK"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.46675968170166,
               61.6216165223706
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SÖRSUNDET"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.509546279907223,
               61.70106395638044
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SNÄCKEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.176737785339355,
               61.41943380537809
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "KRÅKNÄS"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.152791023254395,
               61.416744201264635
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "STENÖ HAVSBAD"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.19433307647705,
               61.24681070163888
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "ORSUNDET"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.259178161621094,
               61.2408440504558
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "ENSKÄR"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.275056838989258,
               61.236012091513985
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "UTVALNÄS UDDE"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.352797985076904,
               60.75184245425473
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "HOLMUDDEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.31819748878479,
               60.73193751350746
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "BRÄDVIKEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.262074947357178,
               60.715589036187716
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "KLÄCKEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.443993091583252,
               60.643800880476675
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "RULLSAND"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.471630573272705,
               60.64057127589496
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SALNÖ"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.992378711700436,
               59.90528466157977
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "KAPELLSKÄR"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               19.06505584716797,
               59.71725079037241
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "BROMSKÄR"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.98782968521118,
               59.62659657131834
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "DEGERSAND"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               19.59664821624756,
               60.154279012328594
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SANDMO"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               19.544527530670166,
               60.21805468151456
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SKJULET"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               19.945592880249023,
               60.10777219078806
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "LUMPARN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               20.141136646270752,
               60.09006909172053
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "PRÄSTÖ"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               20.252351760864258,
               60.205806310826326
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "HÄGERNÄSBADET"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.130273818969727,
               59.44230427475132
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "NÄSAÄNG S"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.105039596557617,
               59.42598016850304
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "STICKLINGE"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.11173439025879,
               59.389790292197006
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "FÅGELÖUDDE"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.23082447052002,
               59.37626103836555
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SÄTRA BADET"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.891535758972168,
               59.286907015650144
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "MJÖLKUDDEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.302600383758545,
               59.313073188611284
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "ERSTAVIK"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.26453447341919,
               59.269268968486266
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "TRINNTORP"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.3566951751709,
               59.228218868854746
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SANDHOLMEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.416733741760254,
               59.19637281570774
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "GRÖNSKAN
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.48023772239685,
               59.22269091300181
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "LILLA SAND"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.52410793304443,
               59.215410431168
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "BJÖRKVIK"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.537476062774658,
               59.220593678551
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "TORPESAND"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.549749851226807,
               59.221527018699234
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "DALARÖ"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.398473262786865,
               59.137556207182165
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "GÅLÖ"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.322019577026367,
               59.09876644287373
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "ÖRUDDEN N"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.791242599487305,
               58.80142826384218
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "ÖRUDDEN V"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.79158592224121,
               58.797204232204024
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "ÖRUDDEN S"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.80986785888672,
               58.798893906561524
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "VACCUM"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               17.11116313934326,
               58.7238242546781
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "VARPET"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               19.221439361572266,
               57.98671907887375
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "EKEVIKEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               19.24633026123047,
               57.97361262244836
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SKÄR"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               19.30400848388672,
               57.986173072238756
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SKALASAND"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               19.337310791015625,
               57.9565852760702
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SUDERSAND"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               19.26074981689453,
               57.9519400506774
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SAXRIV"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.89373779296875,
               57.9285453890267
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SJÖKROGEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.949828147888184,
               57.787216320771336
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "ST OLOFSHOLM"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.91043186187744,
               57.720767154049
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "HIDEVIKEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.878695964813232,
               57.73593619688975
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SLITE"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.80970954895019,
               57.72019418037458
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "IREVIKEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.60285758972168,
               57.84319782592739
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SNÄCK"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.33266258239746,
               57.67356959155067
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "NORDERSTRAND"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.303340673446655,
               57.65307639899865
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "FRIDHEM"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.211727142333984,
               57.5998065794433
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "ÅMINNE"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.76688003540039,
               57.61392296101988
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "KATTVIK"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.854384422302246,
               57.43483323184754
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "GROOGARN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.89897346496582,
               57.436958328679765
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "NATVIKSUDD S"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.917598724365234,
               57.403219401743925
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SANDVIKEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.88103485107422,
               57.39466418725904
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "VÄSTVIKEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.867988586425778,
               57.39864145432571
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "JRP"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.85442733764648,
               57.396606627428056
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SJAUSTRU"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.797414302825928,
               57.374146659910544
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "ARDREVIKEN S"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.780934810638424,
               57.371474141451046
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "LJUGARN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.71568202972412,
               57.33557874994003
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "LAUSVIKEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.66652250289917,
               57.28353126700603
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "GANSVIKEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.430681228637695,
               57.12394135881104
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "FALUDDEN N"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.34193229675293,
               57.01555240433014
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "FALUDDEN S"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.37240219116211,
               56.99704382794897
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "HOLMHÄLLAR"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.278460502624508,
               56.9290299749154
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "SSSS"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.236703872680664,
               57.03266230446723
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "NISSEVIKEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.217241764068604,
               57.1313369287911
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "TJURUDDEN"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.166022300720215,
               57.396306018421306
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "name": "KOVIK"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.155722618103024,
               57.40557751507634
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "namn": "VÄSTERGARN N"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.141968250274658,
               57.436923681351566
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "namn": "TOFTA S"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.126068115234375,
               57.48363310504586
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "namn": "STRANDPANGET"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.12722682952881,
               57.48898465966848
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "namn": "GNIDSVÄRD"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.113794326782223,
               57.500861385987896
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "namn": "SSSSS"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               19.00733470916748,
               57.75677752432833
            ]
         }
      },
      {
         "type":"Feature",
         "properties":{
           "namn": "VÄSTERGARN S"
            "marker-color":"#7e7e7e",
            "marker-size":"small",
            "marker-symbol":""
         },
         "geometry":{
            "type":"Point",
            "coordinates":[
               18.14488649368286,
               57.43262715838854
            ]
         }
      }
   ]
}
*/